Onboarding Pages Added
Anikardava97/Collaboration3_iBanApp pull request #3
Opened 2024-01-12 17:50 UTC by Agladze-Tekla

1) გავაკეთე onboarding გვერდის მოდელი;
2) შევქმენი გვერდების view;
3) გავასწორეთ ნავიგაცია/შევქმენით OnboardingButton;
4) დავაორგანიზე კოდი.

2024-01-12 17:58 UTC, luk407 commented on Collaboration3_iBanProject/Onboarding/OnboardingView.swift
> +    //Functions
1) მარკები არაა, უბრალოდ კომენტარებია. 2) methods და არა functions

2024-01-12 18:07 UTC, luk407 approved these changes
მთლიანობაში ნაის. კარგი იქნებოდა 1 ვიუმოდელი ყოფილიყო და იქ ყოფილიყო ცვლადებიც, იუზერდეფოლტში შენახვის ამბებიც და ა.შ. მარა გასაგები მიზეზების გამო არაუშავს :)

2024-01-12 19:12 UTC, Tparuna1 commented on Collaboration3_iBanProject/Onboarding/OnboardingView.swift
> +    //Functions
კომენტარები არ დატოვო კოდში <3

2024-01-12 19:18 UTC, Tparuna1 reviewed
მომეწონა, რეფაქტორის დროს ჩავასწოროთ თუ რაიმე იყო ჩასასწორებელი. ერთადერთი გადახედე კიდევ კომენტარები არ დაგრჩეს

2024-01-12 19:18 UTC, Tparuna1 commented on Collaboration3_iBanProject/Onboarding/OnboardingView.swift
> +    //Buttons
ესეც კომენტარია

2024-01-13 12:02 UTC, aberidze requested changes
კარგი იყო კოდის მხრივ ყველაფერი <3 ერთ ორ ადგილას გაქვს ნაკლებად მნიშვნელოვანი ხარვეზი და ნახე აბა, სადაც დავაკომენტარე

2024-01-13 12:02 UTC, aberidze commented on Collaboration3_iBanProject/Login/LoginView.swift
> +//TODO: REMOVE COMMENT
ამის გასწორება გამოგრჩა ეტყობა

2024-01-13 12:02 UTC, aberidze commented on Collaboration3_iBanProject/Onboarding/Model/PageModel.swift
> +import SwiftUI
ორივეს იმპორტი არუნდა წესით (SwiftUI მოიცავს Foundations-ს, თუ სწორად მახსოვს)

2024-01-13 12:19 UTC, Anikardava97 approved these changes
თეკლა კარგია ძალიან <3 რაღაც ვიუები შეგვიძლია ჩავშალოთ და userdefault-ს ამბებია გასასწორებელი <3

2024-01-13 12:19 UTC, Anikardava97 commented on Collaboration3_iBanProject/Onboarding/OnboardingView.swift
> +            .tag(page.tag)
ეს ვისტეკიც ცალკე რომ გავიტანოთ კარგი იქნება

2024-01-13 12:19 UTC, Anikardava97 commented on Collaboration3_iBanProject/Onboarding/PageView.swift
> +        }
ესეც ჩავშალოთ

2024-01-13 12:23 UTC, Tparuna1 approved these changes

2024-01-13 12:30 UTC, merged